baseURL = 'https://manueladragic.github.io/swh/'
languageCode = 'en-us'
title = 'Sketching with Hardware I'

[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke"
    disable=false